
import { Article, Book, FeedSourceType } from '../types';

const STORAGE_KEY = 'scidigest_data_v1';
const INTERESTS_KEY = 'scidigest_interests_v1';

const DEFAULT_INTERESTS = [
  "General Science",
  "Mathematics",
  "Technology"
];

const INITIAL_ARTICLES: Article[] = [
  {
    id: 'example-1',
    title: 'Sample Research Article Title',
    authors: ['Author A.', 'Author B.'],
    abstract: 'This is a placeholder abstract. Once you start ingesting papers from your feeds, your library will populate with real research data.',
    date: '2024-01-01',
    year: '2024',
    source: FeedSourceType.MANUAL,
    rating: 5,
    userReviews: {
      sentiment: 'Neutral',
      summary: 'This is a sample review summary generated by the system.',
      lastUpdated: '2024-01-01',
      citationCount: 0,
    },
    tags: ['Example'],
    isBookmarked: false,
    notes: 'Welcome to SciDigest AI.'
  }
];

export const dbService = {
  getData: () => {
    const data = localStorage.getItem(STORAGE_KEY);
    if (!data) return { articles: INITIAL_ARTICLES, books: [] };
    const parsed = JSON.parse(data);
    parsed.articles = (parsed.articles || []).map((a: any) => ({
      ...a,
      year: a.year || (a.date ? a.date.split('-')[0] : 'N/A'),
      userReviews: a.userReviews || { sentiment: 'Unknown', summary: 'No review data yet.' }
    }));
    return parsed;
  },
  saveData: (data: any) => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  },
  getInterests: (): string[] => {
    const stored = localStorage.getItem(INTERESTS_KEY);
    return stored ? JSON.parse(stored) : DEFAULT_INTERESTS;
  },
  saveInterests: (interests: string[]) => {
    localStorage.setItem(INTERESTS_KEY, JSON.stringify(interests));
  },
  addArticle: (article: Article) => {
    const data = dbService.getData();
    data.articles.unshift(article);
    dbService.saveData(data);
    return data;
  },
  updateArticle: (id: string, updates: Partial<Article>) => {
    const data = dbService.getData();
    data.articles = data.articles.map((a: Article) => a.id === id ? { ...a, ...updates } : a);
    dbService.saveData(data);
    return data;
  },
  addBooks: (newBooks: Book[]) => {
    const data = dbService.getData();
    data.books = [...newBooks, ...data.books];
    dbService.saveData(data);
    return data;
  }
};
